services:
  backend:
    build:
      context: ./backend
    container_name: pasti-backend
    env_file:
      - ./backend/.env
    ports:
      - "8686:8686"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - pasti-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8686/api/v1
        NEXT_PUBLIC_API_ROOT_URL: http://localhost:8686
    container_name: pasti-frontend
    ports:
      - "3000:3000"
    networks:
      - pasti-network
    restart: unless-stopped
    depends_on:
      - backend

networks:
  pasti-network:
    driver: bridge