services:
  backend:
    build:
      context: ./backend
    container_name: pasti-backend
    env_file:
      - .env.prod
    expose:
      - "8686"
    networks:
      - pasti-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: https://pasti.kemenkeu.go.id/api/v1
        NEXT_PUBLIC_API_ROOT_URL: https://pasti.kemenkeu.go.id
    container_name: pasti-frontend
    expose:
      - "3000"
    networks:
      - pasti-network
    restart: unless-stopped
    depends_on:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:1.27-alpine
    container_name: pasti-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    networks:
      - pasti-network
    restart: unless-stopped
    depends_on:
      - backend
      - frontend

  certbot:
    image: certbot/certbot
    container_name: pasti-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  pasti-network:
    driver: bridge