IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'inaproc_paket_penyedia_terumumkan')
BEGIN
    CREATE TABLE inaproc_paket_penyedia_terumumkan (
        row_key NVARCHAR(255) PRIMARY KEY,
        alasan_dikecualikan NVARCHAR(500) NULL,
        alasan_non_ukm NVARCHAR(500) NULL,
        jenis_klpd NVARCHAR(100) NULL,
        jenis_pengadaan NVARCHAR(255) NULL,
        kd_jenis_pengadaan NVARCHAR(20) NULL,
        kd_klpd NVARCHAR(20) NULL,
        kd_metode_pengadaan NVARCHAR(20) NULL,
        kd_rup NVARCHAR(50) NULL,
        kd_rup_lokal NVARCHAR(50) NULL,
        kd_rup_swakelola NVARCHAR(50) NULL,
        kd_satker NVARCHAR(50) NULL,
        kd_satker_str NVARCHAR(50) NULL,
        kode_rup_tahun_pertama NVARCHAR(50) NULL,
        metode_pengadaan NVARCHAR(255) NULL,
        nama_klpd NVARCHAR(255) NULL,
        nama_paket NVARCHAR(500) NULL,
        nama_ppk NVARCHAR(255) NULL,
        nama_satker NVARCHAR(255) NULL,
        nip_ppk NVARCHAR(50) NULL,
        nomor_kontrak NVARCHAR(255) NULL,
        pagu BIGINT NULL,
        spesifikasi_pekerjaan NVARCHAR(MAX) NULL,
        spp_aspek_ekonomi BIT NULL,
        spp_aspek_lingkungan BIT NULL,
        spp_aspek_sosial BIT NULL,
        status_aktif_rup BIT NULL,
        status_delete_rup BIT NULL,
        status_dikecualikan BIT NULL,
        status_konsolidasi NVARCHAR(100) NULL,
        status_pdn NVARCHAR(100) NULL,
        status_pradipa NVARCHAR(100) NULL,
        status_ukm NVARCHAR(100) NULL,
        status_umumkan_rup NVARCHAR(100) NULL,
        tahun_anggaran NVARCHAR(10) NULL,
        tahun_pertama NVARCHAR(10) NULL,
        tgl_akhir_kontrak DATETIME2 NULL,
        tgl_akhir_pemanfaatan DATETIME2 NULL,
        tgl_akhir_pemilihan DATETIME2 NULL,
        tgl_awal_kontrak DATETIME2 NULL,
        tgl_awal_pemanfaatan DATETIME2 NULL,
        tgl_awal_pemilihan DATETIME2 NULL,
        tgl_buat_paket DATETIME2 NULL,
        tgl_pengumuman_paket DATETIME2 NULL,
        tipe_paket NVARCHAR(50) NULL,
        uraian_pekerjaan NVARCHAR(MAX) NULL,
        username_ppk NVARCHAR(100) NULL,
        volume_pekerjaan NVARCHAR(255) NULL,
        synced_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
    );

    CREATE INDEX idx_ippt_kd_klpd_tahun ON inaproc_paket_penyedia_terumumkan(kd_klpd, tahun_anggaran);
    CREATE INDEX idx_ippt_kd_satker ON inaproc_paket_penyedia_terumumkan(kd_satker);
    CREATE INDEX idx_ippt_status_umumkan ON inaproc_paket_penyedia_terumumkan(status_umumkan_rup);
END;